;;;
;;;
;;;
;;;
;;;
;;;se variavel Uc ambiental for sim, acrescesntar na lista
;;;"Anexar autorização de acesso concedida pelo orgão responsavel pela Unidade conservação"
;;;se variavel corte arvore ou faixa for sim
;;;"Colocar nota no projeto sobre supressão vegetal conforme indicação"
;;;
;;;
;;;se variavel telefone for diferentente vazio
;;;"Colocar numero de contato cliente no projeto"
;;;
;;;se variavel CAD unico for sim
;;;"Cliente possui CAD unico, orçar padrão de entrada"
;;;"colocar nota sobre CAD unico no projeto"
;;;
;;; variavel financiamento padrão
;;;"Colocar texto sobre financiamento padrão no projeto"
;;;
;;; variavel linha viva sim -
;;;"Colocar texto dizendo que foi orçado linha-viva"
;;;
;;;
;;; variavel acesso ao local
;;;"Colocar informação sobre acesso ao local no projeto"
;;;
;;; variavel carga instalada
;;;se carga instalada for maior que 50kw, colocar no check
;;;"Enviar orçamento partic. Financeira Cliente"
;;;
;;;
;;;
;;;(if
;;;
;;;  xxxxx "MT10"
;;;
;;;
;;;  (setq lst9 (list
;;;
;;;sdfsadfasdfsadfkjsaçlkdjfçslakjfojsaçlkfjsadf46465431645a       tamanho maximo
;;;"Inserir KML do traçado da rede"
;;;"Colocar nota sobre licenciamento ambiental no projeto"
;;;"Verificar traçado da res"
;;;"Verificar classificação correta do PI"
;;;
;;;
